<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.8.10 on linux)" generated="20240111 18:30:25.836" rpa="false" schemaversion="4">
<suite id="s1" name="Alerts" source="/home/ridham/PycharmProjects/webAutomation/Exercise3/Tests/Alerts.robot">
<test id="s1-t1" name="Launch Browser" line="15">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>https://demoqa.com/</arg>
<arg>chrome</arg>
<arg>options=add_experimental_option("detach", True)</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20240111 18:30:25.984" level="INFO">Opening browser 'chrome' to base url 'https://demoqa.com/'.</msg>
<msg timestamp="20240111 18:30:33.161" level="WARN">There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Connection reset by peer (os error 104)); using driver found in the cache</msg>
<status status="PASS" starttime="20240111 18:30:25.983" endtime="20240111 18:30:39.132"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20240111 18:30:39.133" endtime="20240111 18:30:39.237"/>
</kw>
<status status="PASS" starttime="20240111 18:30:25.982" endtime="20240111 18:30:39.239"/>
</test>
<test id="s1-t2" name="Open Alerts,Frames Section" line="19">
<kw name="Execute Javascript" library="SeleniumLibrary">
<arg>document.querySelectorAll('div.card.mt-4.top-card')[2].click();</arg>
<doc>Executes the given JavaScript code with possible arguments.</doc>
<msg timestamp="20240111 18:30:39.245" level="INFO">Executing JavaScript:
document.querySelectorAll('div.card.mt-4.top-card')[2].click();
Without any arguments.</msg>
<status status="PASS" starttime="20240111 18:30:39.242" endtime="20240111 18:30:39.337"/>
</kw>
<kw name="Sleep" library="BuiltIn">
<arg>3s</arg>
<doc>Pauses the test executed for the given time.</doc>
<msg timestamp="20240111 18:30:42.338" level="INFO">Slept 3 seconds</msg>
<status status="PASS" starttime="20240111 18:30:39.337" endtime="20240111 18:30:42.339"/>
</kw>
<kw name="Perform Action for Browser Window">
<kw name="Execute Javascript" library="SeleniumLibrary">
<arg>document.querySelectorAll('#item-0')[2].click();</arg>
<doc>Executes the given JavaScript code with possible arguments.</doc>
<msg timestamp="20240111 18:30:42.346" level="INFO">Executing JavaScript:
document.querySelectorAll('#item-0')[2].click();
Without any arguments.</msg>
<status status="PASS" starttime="20240111 18:30:42.344" endtime="20240111 18:30:42.405"/>
</kw>
<kw name="Click Button" library="SeleniumLibrary">
<arg>${NEWTAB}</arg>
<doc>Clicks the button identified by ``locator``.</doc>
<msg timestamp="20240111 18:30:42.406" level="INFO">Clicking button 'Xpath://*[@id="tabButtonWrapper"]'.</msg>
<msg timestamp="20240111 18:30:42.712" level="INFO" html="true">&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan="3"&gt;&lt;a href="selenium-screenshot-10.png"&gt;&lt;img src="selenium-screenshot-10.png" width="800px"&gt;&lt;/a&gt;</msg>
<msg timestamp="20240111 18:30:42.712" level="FAIL">Button with locator 'Xpath://*[@id="tabButtonWrapper"]' not found.</msg>
<status status="FAIL" starttime="20240111 18:30:42.405" endtime="20240111 18:30:42.713"/>
</kw>
<status status="FAIL" starttime="20240111 18:30:42.340" endtime="20240111 18:30:42.713"/>
</kw>
<status status="FAIL" starttime="20240111 18:30:39.240" endtime="20240111 18:30:42.714">Button with locator 'Xpath://*[@id="tabButtonWrapper"]' not found.</status>
</test>
<status status="FAIL" starttime="20240111 18:30:25.837" endtime="20240111 18:30:42.714"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="1" skip="0" id="s1" name="Alerts">Alerts</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240111 18:30:33.161" level="WARN">There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Connection reset by peer (os error 104)); using driver found in the cache</msg>
</errors>
</robot>
